name: "CI/CD Standard (BlauwTech)"

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node (opcional)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Ejecutar lint (si está configurado)
        run: |
          if [ -f package.json ]; then
            npm ci
            npm run lint --if-present
          else
            echo "No hay configuración de lint para Node detectada."
          fi

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - name: Ejecutar Trivy (escaneo de ficheros)
        uses: aquasecurity/trivy-action@v2
        with:
          scan-type: fs
          format: json
          output: trivy-report.json
          severity: CRITICAL,HIGH
          exit-code: '1'
      - name: Subir informe Trivy
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json

  deploy:
    name: Deploy (placeholder)
    runs-on: ubuntu-latest
    needs: [lint, security-scan]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy placeholder
        run: |
          echo "Implementar pasos de despliegue aquí (proveedor, envs, aprobaciones)."

# Notas:
# - Esta plantilla es un molde genérico. Personaliza pasos de linting y deployment según el stack del repositorio.
# - Trivy es usado como escáner OSS; ajusta severities y comportamiento de exit-code según política de seguridad.
